### ISSUE TITLE
OSError: no version directory for Xilinx tools found in /opt/Xilinx

### ISSUE THREAD

**Issue by wxh0000mm** [openvizsla/ov_ftdi#20]
hello
I have an error running MAKE in the OV3 folder

king@king-virtual-machine:~/桌面/ov_ftdi/software/fpga/ov3$ make
python3 build.py build_dir=build build_name=ov3
Traceback (most recent call last):
  File "build.py", line 34, in <module>
    plat.build(top, **dict(arg.split('=') for arg in sys.argv[1:]))
  File "/usr/local/lib/python3.5/dist-packages/migen-0.8.dev0-py3.5.egg/migen/build/xilinx/platform.py", line 43, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/migen-0.8.dev0-py3.5.egg/migen/build/xilinx/ise.py", line 209, in build
    ngdbuild_opt, self, platform)
  File "/usr/local/lib/python3.5/dist-packages/migen-0.8.dev0-py3.5.egg/migen/build/xilinx/ise.py", line 99, in _run_ise
    settings = common.settings(ise_path, ver, "ISE_DS")
  File "/usr/local/lib/python3.5/dist-packages/migen-0.8.dev0-py3.5.egg/migen/build/xilinx/common.py", line 39, in settings
    + path)
OSError: no version directory for Xilinx tools found in /opt/Xilinx
Makefile:18: recipe for target 'build/ov3.bit' failed
make: *** [build/ov3.bit] Error 1

Which version of Xilinx is used?What should I do to compile properly.

**Comment by ar0mat** [comment]
Hello.

I used the latest version of Xilinx ISE. I remember I was installing the ISE according to this tutorial https://www.youtube.com/watch?v=meO-b6Ib17Y

**Comment by wxh0000mm** [comment]
@ar0mat It is installed according to the video you provided. Thank you.
