### ISSUE TITLE
Error in building ov_ftdi

### ISSUE THREAD

**Issue by jeffreyantony** [openvizsla/ov_ftdi#4]
I tried to build ov_ftdi. I gave a 'make' in the folder 'ov_ftdi/software/fpga/ov3' and got the below error

Could you let me know how can I remove the below error? I am not sure if I  have an updated 'NetowrkX'. 

Is it possible for you to update to the new Migen ?

$ make
python3 build.py build_dir build build_name ov3
Traceback (most recent call last):
  File "build.py", line 24, in <module>
    top = OV3(plat)
  File "/home/robo/tools/ov_ftdi/software/fpga/ov3/ovhw/top.py", line 119, in __init__
    [self.randtest, self.sdram_host_read])
  File "/home/robo/tools/ov_ftdi/software/fpga/ov3/ovhw/cmdproc.py", line 37, in __init__
    self.submodules.fg = CompositeActor(g)
  File "/home/robo/tools/ov_ftdi/software/fpga/migen/migen/flow/network.py", line 222, in __init__
    dfg.elaborate()
  File "/home/robo/tools/ov_ftdi/software/fpga/migen/migen/flow/network.py", line 215, in elaborate
    self._eliminate_subrecords_and_divergences()
  File "/home/robo/tools/ov_ftdi/software/fpga/migen/migen/flow/network.py", line 129, in _eliminate_subrecords_and_divergences
    for (dst_node, dst_endpoint), sources in self._sink_to_sources().items():
  File "/home/robo/tools/ov_ftdi/software/fpga/migen/migen/flow/network.py", line 101, in _sink_to_sources
    for u, v, data in self.edges_iter(data=True):
AttributeError: 'DataFlowGraph' object has no attribute 'edges_iter'
Makefile:18: recipe for target 'build/ov3.bit' failed
make: *** [build/ov3.bit] Error 1

**Comment by Goddard** [comment]
I think the main maintainer passed away.  If anything is going to happen it is gonna have to be us.
