### ISSUE TITLE
LibOV.ProtocolError: Checksum for response incorrect

### ISSUE THREAD

**Issue by defencore** [openvizsla/ov_ftdi#53]
When I try to sniff traffic between the Android and the DJI RC, I get an error:

```
# Board: OpenVizsla v3.3
└─$ ./software/host/ovctl.py -l sniff hs
```

```
PERR: 1FD0 (First)
[   F    ]  11.586765 d=  0.007282 [178   +1688811.583] [  0]  
Exception in thread Thread-1 (__comms):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ov_ftdi/software/host/LibOV.py", line 637, in __comms
    raise self.__comm_exc
  File "/tmp/ov_ftdi/software/host/LibOV.py", line 616, in callback
    code = service.presentBytes(self.__buf)
  File "/tmp/ov_ftdi/software/host/LibOV.py", line 310, in presentBytes
    self.consume(b[:size])
  File "/tmp/ov_ftdi/software/host/LibOV.py", line 332, in consume
    raise ProtocolError(
LibOV.ProtocolError: Checksum for response incorrect: expected 76, got 01
```

**Comment by desowin** [comment]
Is this related to #13? Do you get similar issue when using [ovextcap](https://github.com/matwey/libopenvizsla/tree/master/tools/ovextcap)? The libopenvizsla [unconditionally forces firmware download](https://github.com/matwey/libopenvizsla/pull/27) while ov_ftdi does not.
